### ISSUE TITLE
undefined method `delete_intArray' for Cbc_wrapper:Module

### ISSUE THREAD

**Issue by ashleyHutton** [gverger/ruby-cbc#24] opened 2022-08-01 14:57 UTC
We've been using this library with great success to speed up our large computations in one of our projects. But we've been seeing this error message:

```/usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/conversions.rb:55: warning: Exception in finalizer #<Proc:0x00007fd2276fa7b0 /usr/local/bundle/gems/ruby-cbc-0.3.18/lib/ruby-cbc/problem.rb:186>
/usr/local/bundle/gems/ruby-cbc-0.3.18/lib/ruby-cbc/problem.rb:188:in `block (2 levels) in finalizer': undefined method `delete_intArray' for Cbc_wrapper:Module (NoMethodError)

        int_arrays.each { |ar| Cbc_wrapper.delete_intArray(ar) }
                                          ^^^^^^^^^^^^^^^^
        from /usr/local/bundle/gems/ruby-cbc-0.3.18/lib/ruby-cbc/problem.rb:188:in `each'
        from /usr/local/bundle/gems/ruby-cbc-0.3.18/lib/ruby-cbc/problem.rb:188:in `block in finalizer'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/conversions.rb:55:in `strftime'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/core_ext/time/conversions.rb:55:in `to_formatted_s'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:123:in `quoted_date'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/quoting.rb:56:in `quoted_date'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:245:in `_type_cast'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/quoting.rb:162:in `_type_cast'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:43:in `type_cast'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:205:in `block in type_casted_binds'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `map'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/quoting.rb:203:in `type_casted_binds'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:669:in `exec_no_cache'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:649:in `execute_and_clear'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:55:in `exec_query'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:136:in `exec_insert'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:93:in `exec_insert'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:171:in `insert'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `insert'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:375:in `_insert_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:929:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/counter_cache.rb:166:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/locking/optimistic.rb:79:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/attribute_methods/dirty.rb:201:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/callbacks.rb:461:in `block in _create_record'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:106:in `run_callbacks'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_create_callbacks'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/callbacks.rb:461:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/timestamp.rb:108:in `_create_record'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:900:in `create_or_update'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/callbacks.rb:457:in `block in create_or_update'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/autosave_association.rb:385:in `around_save_collection_association'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:824:in `_run_save_callbacks'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/callbacks.rb:457:in `create_or_update'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/timestamp.rb:126:in `create_or_update'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/persistence.rb:507:in `save!'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/validations.rb:53:in `save!'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:302:in `block in save!'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/transactions.rb:302:in `save!'
        from /usr/local/bundle/gems/activerecord-6.1.6.1/lib/active_record/suppressor.rb:48:in `save!'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/evaluation.rb:18:in `create'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:12:in `block in result'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:9:in `result'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory.rb:43:in `run'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:28:in `run'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
        from /app/spec/factories/facilities.rb:52:in `block (3 levels) in <main>'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/callback.rb:13:in `instance_exec'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/callback.rb:13:in `run'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/callbacks_observer.rb:11:in `block in update'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/callbacks_observer.rb:10:in `each'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/callbacks_observer.rb:10:in `update'
        from /usr/local/lib/ruby/3.1.0/observer.rb:222:in `block in notify_observers'
        from /usr/local/lib/ruby/3.1.0/observer.rb:221:in `each'
        from /usr/local/lib/ruby/3.1.0/observer.rb:221:in `notify_observers'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/evaluation.rb:24:in `notify'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:13:in `block in result'
        from <internal:kernel>:90:in `tap'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy/create.rb:9:in `result'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory.rb:43:in `run'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:29:in `block in run'
        from /usr/local/bundle/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:205:in `instrument'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/factory_runner.rb:28:in `run'
        from /usr/local/bundle/gems/factory_bot-6.2.1/lib/factory_bot/strategy_syntax_method_registrar.rb:28:in `block in define_singular_strategy_method'
        from /app/spec/models/optimization_spec.rb:37:in `block (3 levels) in <top (required)>'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block (2 levels) in let'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (3 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (2 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-support-3.11.0/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:178:in `block in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block in let'
        from /app/spec/models/optimization_spec.rb:31:in `block (3 levels) in <top (required)>'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block (2 levels) in let'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (3 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (2 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-support-3.11.0/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:178:in `block in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block in let'
        from /app/spec/models/optimization_spec.rb:19:in `block (3 levels) in <top (required)>'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block (2 levels) in let'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (3 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:179:in `block (2 levels) in fetch_or_store'
        from /usr/local/bundle/gems/rspec-support-3.11.0/lib/rspec/support/reentrant_mutex.rb:23:in `synchronize'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:178:in `block in fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:177:in `fetch_or_store'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:343:in `block in let'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/memoized_helpers.rb:402:in `block in let!'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:365:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:529:in `block in run_owned_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `each'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:528:in `run_owned_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:615:in `block in run_example_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `reverse_each'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:614:in `run_example_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:484:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:505:in `run_before_example'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:261:in `block in run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
        from /usr/local/bundle/gems/rspec-rails-5.1.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
        from /usr/local/bundle/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
        from /usr/local/bundle/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
        from /usr/local/bundle/bin/rspec:25:in `load'
        from /usr/local/bundle/bin/rspec:25:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli.rb:483:in `exec'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli.rb:31:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/cli.rb:25:in `start'
        from /usr/local/bundle/gems/bundler-2.3.19/exe/bundle:48:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.3.19/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.3.19/exe/bundle:36:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
```

We're using these versions of `ruby-cbc` and `cbc-wrapper`:
`ruby-cbc (0.3.18)`
`cbc-wrapper (2.9.9.4)`

It looks like the `delete_intArray` method is not listed in the `Cbc_C_interface.h` in the [cbc-wrapper](https://github.com/gverger/cbc-wrapper/tree/v2.9.9.4) readme, so the error message makes sense. This also happens in the `finalizer` class method, so we're not actually seeing incorrect results from this. But, it is making our logs pretty difficult to read. We'd appreciate any help!

**Comment by gverger** [comment] 2022-08-01 16:22
Hello,

Thanks for using ruby-cbc. To be honest I am very rusty with this gem right now, especially the C embedding part.

Do you have any (small) example of it that you could share so that I can reproduce this issue?

The method `delete_intArray` is indeed not in the interface. From what I recall, it is defined by SWIG, which helps with the interface Ruby <-> C, and you can find a method that is almost named the same [in file cbc_wrap.c](https://github.com/gverger/cbc-wrapper/blob/master/ext/cbc-wrapper/cbc_wrap.c#L2166) which is automatically generated by swig.

It seems that this method is undefined when trying to call it from ruby too and I have no clue about how to call it.

What we want to do in the `problem.rb` class is that we want to free the memory used to store C arrays (int and double), because when GC runs, it doesn't free the memory of these objects automatically.

There might be a way to do it, but as I said, it's been a long time since I digged into this kind of problems.

I will try to search for a way to solve this problem, but don't expect too much please. In the meantime, if you have an example where this issue happens consistently, I'd be happy to study it.

**Comment by ashleyHutton** [comment] 2022-08-01 17:43
@gverger thanks for the response! I will work on finding a simple example for you to test.

> What we want to do in the problem.rb class is that we want to free the memory used to store C arrays (int and double), because when GC runs, it doesn't free the memory of these objects automatically.

I was a big confused by this note. I was reading through the [SWIG documentation for ruby](https://swig.org/Doc1.3/Ruby.html#Ruby_nn57), specifically the section about [Free functions](https://swig.org/Doc1.3/Ruby.html#Ruby_nn62). From reading those docs, it seems like the `delete_IntArray` method would be called automatically when the `free_IntArray` is called - which is triggered by the Ruby GC. Is there a reason that the arrays in `problem.rb` would not call the `free` method automatically when they are garbage collected? This is pretty unfamiliar territory for me, so please let me know what I'm missing. :)

**Comment by gverger** [comment] 2022-08-01 18:52
You might be right. I think I once saw [this](https://github.com/wtaysom/rglpk/pull/2/files) amongst other things and it made me realize that it is possible these arrays are not freed.

But in our case we use `Cbc_wrapper::IntArray.new(array.size)` instead of something like `Cbc_wrapper.new_intArray(array.size)` and since it is in a new object, it would be automatically freed.

It seems I need to do some tests about it.

**Comment by gverger** [comment] 2022-08-03 17:04
I ran some tests (in branch [test-memory-leak](https://github.com/gverger/ruby-cbc/tree/test-memory-leak)) where I checked if we really need to manually free these arrays.

It seems that we don't need to free them indeed. The only thing we must free is the Cbc C model.

I have been unable to reproduce your bug though, the method `Cbc_wrapper.delete_intArray` seems to exist.

What I will probably do is delete these 2 lines in the finalizer, and your problem will vanish. The only problem with that is that I still don't understand what is going on with the undefined method exception.

**Comment by ashleyHutton** [comment] 2022-08-03 21:14
Oh, that's great news! I was able to find a pretty minimal example that throws the error in my rails console:

```ruby
m = Cbc::Model.new
m.int_var_array(2, 0..1)
m.to_problem.solve
Array.new(8760, 0)
```

After I initialize the array, I see the error message. Our project works with hourly data, which we store as arrays of 8,760 data points. We're seeing this error pretty consistently in our specs. It to seems to be related to the size of the array, because I'm not able to reproduce it with an array of only 100 elements.

Let me know if you're able to see similar results.

**Comment by gverger** [comment] 2022-08-03 22:19
Thanks for the code sample. Unfortunately I have not been able to reproduce the error, even with large arrays.
Do you mean that after you enter `Array.new(8760, 0)` in the console, the error kicks in?

What do you run ruby-cbc on?
What version of cbc do you have installed?


On another note, I've pushed version 0.3.19 of the gem with no manual freeing of these arrays, please give it a try!

**Comment by gverger** [comment] 2022-09-20 16:17
I am closing this issue since there is no message anymore. Feel free to reopen it in case it is not solved...

**Closed by gverger** 2022-09-20 16:17 UTC
